apiVersion: v1
kind: Service
metadata:
  name: test-cube-cluster-service
spec:
  selector:
    app: test-cube
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      # Gotcha: NodePort range is typically 30000-32767.
      nodePort: 30001
  type: NodePort
